
BEC - BitEtherCoin
==================

BEC (BitEtherCoin) is an Ethereum Classic coin, issued per each block as a reward to the miner.


It follows Bitcoin's coin Supply Model, with:

* 21M BEC coins total
* 0.00000001 BEC = 1 BECsatoshi
* Halving each new era
* 7th era (99.2% coins) ends at about 2034 (for BTC it's 2036)
* 13th era (99.99% coins) ends at 2048 (for BTC it's 2060)

Specific details:

* mining starts at block 2,726,892
* Era size is 5250000 Ethereum blocks
* starts with 2 BEC reward per ETC block (instead of 50, because Ethereum block time is much smaller)

To claim block reward there should be a special transaction in the block, which calls contract method `claim()`. This
 transaction could be sent from any address, but only an actual miner for current block will receive reward tokens.

## Address

Mainnet (ETC): 0x085fb4f24031eaedbc2b611aa528f22343eb52db

You can install this address as a standard Ethereum token into your Mist or other wallet (see ABI below).


## Mining BEC Coins

To claim block reward there should be a special transaction in the block, which calls contract method `claim()`. This
 transaction could be sent from any address, but only an actual miner for current block will receive reward tokens.

For example you can send such transaction _before_ each block by execution following command:

----
curl --request POST \
  --url http://localhost:8545/ \
  --header 'content-type: application/json' \
  --data '{"jsonrpc":"2.0", "method":"eth_sendTransaction", "params":[{"from":"0xANY_UNLOCKED_ADDRESS", "to":"0x085fb4f24031eaedbc2b611aa528f22343eb52db", "gas": "0x30d40", "value": "0x0", "data": "0x4e71d92d"}], "id":1}'
----

The problem with this approach that it will cost you some gas to execute this transaction even if you're a miner of the block.
Another way is to patch Parity/Geth to include such transactions automatically, link:miner/[See Example]


## ABI

----
[
  {
    "constant": false,
    "inputs": [],